(function(){
const app=document.getElementById('app'), DEFAULT=window.GOLD_BRICKS_DEFAULTS;let sb=null,current=null;
try{if(window.SUPABASE_CONFIG?.url?.startsWith('http')&&!window.SUPABASE_CONFIG.anonKey.includes('PASTE_'))sb=window.supabase.createClient(window.SUPABASE_CONFIG.url,window.SUPABASE_CONFIG.anonKey)}catch(e){}
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function ready(){return !!sb}
function login(){app.innerHTML=`<div style="max-width:420px;margin:12vh auto"><h2>Admin login</h2><p class="sub">Use the Supabase Auth email and password created for the site administrator.</p><div class="form-box"><label class="form-field">Email<input id="email" type="email" autocomplete="username"></label><label class="form-field">Password<input id="pass" type="password" autocomplete="current-password"></label><div class="status" id="msg"></div><div class="row" style="display:flex;gap:10px;margin-top:16px"><button class="btn" id="login">Log in</button><a class="btn g" href="index.html">Back</a></div></div></div>`;$('login').onclick=doLogin}
const $=id=>document.getElementById(id);
async function doLogin(){const msg=$('msg');if(!ready()){msg.textContent='Configure config.js first.';return}msg.textContent='Signing in…';const {error}=await sb.auth.signInWithPassword({email:$('email').value.trim(),password:$('pass').value});if(error){msg.textContent=error.message;return}await loadEditor()}
async function loadEditor(){const {data,error}=await sb.from('site_content').select('data').eq('id',true).single();if(error){app.innerHTML='<h2>Could not load site content</h2><p class="status">'+esc(error.message)+'</p>';return}current=data.data;editor()}
function field(parent,label,obj,key,type='text'){const wrap=document.createElement('label');wrap.className='form-field';wrap.textContent=label;const i=document.createElement(type==='area'?'textarea':'input');if(type==='number')i.type='number';i.value=obj[key]??'';i.oninput=()=>obj[key]=type==='number'?Number(i.value):i.value;wrap.appendChild(i);parent.appendChild(wrap)}
function imageField(parent,label,obj,key){const wrap=document.createElement('label');wrap.className='form-field full';wrap.textContent=label;const i=document.createElement('input');i.type='file';i.accept='image/*';const img=document.createElement('img');img.className='preview';img.src=obj[key]||'';i.onchange=()=>{const f=i.files?.[0];if(!f)return;const reader=new FileReader();reader.onload=()=>{obj[key]=reader.result;img.src=obj[key]};reader.readAsDataURL(f)};wrap.append(i,img);parent.appendChild(wrap)}
function section(title){const h=document.createElement('h3');h.textContent=title;app.querySelector('#editor').appendChild(h);const box=document.createElement('div');box.className='form-box';app.querySelector('#editor').appendChild(box);return box}
function list(title,arr,drawItem,blank){const h=document.createElement('h3');h.textContent=title;const editor=document.getElementById('editor');editor.appendChild(h);const holder=document.createElement('div');editor.appendChild(holder);function redraw(){holder.innerHTML='';arr.forEach((item,n)=>{const box=document.createElement('div');box.className='item';const head=document.createElement('div');head.className='item-head';head.innerHTML='<b>Item '+(n+1)+'</b>';const del=document.createElement('button');del.className='danger';del.textContent='Delete';del.onclick=()=>{arr.splice(n,1);redraw()};head.appendChild(del);box.appendChild(head);drawItem(box,item);holder.appendChild(box)})}redraw();const add=document.createElement('button');add.className='btn g';add.textContent='+ Add';add.onclick=()=>{arr.push(structuredClone(blank));redraw()};editor.appendChild(add)}
function editor(){app.innerHTML='<h2>Admin panel</h2><p class="sub">Edit the content and save it to the live database. Changes are shared across devices.</p><div id="editor"></div><div class="admin-bar"><div style="display:flex;gap:10px;flex-wrap:wrap"><button class="btn" id="save">Save changes</button><button class="btn g" id="logout">Log out</button><a class="btn g" href="index.html">View website</a></div><div class="status" id="status"></div></div>';
let b=section('General');field(b,'Company name',current,'brand');field(b,'Small heading above title',current,'kicker');field(b,'Hero title',current,'title');field(b,'Hero text',current,'sub','area');field(b,'WhatsApp number (with 92, no +)',current,'wa');field(b,'Phone shown on site',current,'phone');field(b,'Address',current,'address','area');imageField(b,'Logo',current,'logo');imageField(b,'Hero image',current,'hero');
list('Hero highlights',current.stats,(x,s)=>{field(x,'Number / value',s,0);field(x,'Label',s,1)},['0','Label']);list('Opening hours',current.hours,(x,s)=>{field(x,'Day',s,0);field(x,'Hours',s,1)},['Day','8 AM–10 PM']);list('Properties',current.props,(x,p)=>{field(x,'Title',p,'title');field(x,'Location',p,'loc');field(x,'Price (PKR, full number)',p,'price','number');field(x,'Area',p,'area');field(x,'Bedrooms',p,'beds','number');field(x,'Bathrooms',p,'baths','number');field(x,'Badge',p,'badge');imageField(x,'Photo',p,'img')},{title:'New property',loc:'Islamabad',price:10000000,area:'5 Marla',beds:3,baths:2,badge:'For Sale',img:current.props?.[0]?.img||current.hero});let c=section('About the CEO');field(c,'Name',current.ceo,'name');field(c,'Role',current.ceo,'role');field(c,'Biography',current.ceo,'bio','area');imageField(c,'Photo',current.ceo,'img');list('Reviews',current.reviews,(x,r)=>{field(x,'Name',r,'name');field(x,'Details',r,'meta');field(x,'Review',r,'text','area')},{name:'Client name',meta:'Just now',text:'Review text'});
$('save').onclick=save;$('logout').onclick=async()=>{await sb.auth.signOut();login()}}
async function uploadDataUrls(obj,adminPath='site-assets'){/* Optional future optimization: keep data URLs for now. Supabase row stores the exact edited content, including uploaded images. */return obj}
async function save(){const st=$('status');st.textContent='Saving to database…';try{await uploadDataUrls(current);const {error}=await sb.from('site_content').update({data:current,updated_at:new Date().toISOString()}).eq('id',true);if(error)throw error;st.textContent='Saved. The public website will use the new content on the next load.'}catch(e){st.textContent='Save failed: '+e.message}}
async function start(){if(!ready()){app.innerHTML='<h2>Supabase is not configured</h2><p class="status">Open config.js and add your Supabase project URL and anon/publishable key, then run supabase-schema.sql.</p>';return}const {data}=await sb.auth.getSession();if(data.session)await loadEditor();else login()}
start();
})();
